% AWR1642 레이더 데이터 처리 스크립트
% data/radar/ 에 있는 .bin 파일을 읽어 Range-Doppler 맵 시각화

recordLocation = "D:\projects\RadYOLO\data\radar";

temp = load(fullfile(recordLocation, 'iqData_RecordingParameters.mat'));
dcaRecordingParams = temp.RecordingParameters;

fs         = dcaRecordingParams.ADCSampleRate * 1e3;       % kHz → Hz
sweepSlope = dcaRecordingParams.SweepSlope * 1e12;         % MHz/us → Hz/s
nr         = dcaRecordingParams.SamplesPerChirp;
fc         = dcaRecordingParams.CenterFrequency * 1e9;     % GHz → Hz
tpulse     = 2 * dcaRecordingParams.ChirpCycleTime * 1e-6; % us → s (TDM x2)
prf        = 1 / tpulse;
nrx        = dcaRecordingParams.NumReceivers;
nchirp     = dcaRecordingParams.NumChirps;

rangeresp = phased.RangeResponse( ...
    RangeMethod            = 'FFT', ...
    RangeFFTLengthSource   = 'Property', ...
    RangeFFTLength         = nr, ...
    SampleRate             = fs, ...
    SweepSlope             = sweepSlope, ...
    ReferenceRangeCentered = false);

rdscope = phased.RangeDopplerScope( ...
    IQDataInput            = true, ...
    SweepSlope             = sweepSlope, ...
    SampleRate             = fs, ...
    DopplerOutput          = 'Speed', ...
    OperatingFrequency     = fc, ...
    PRFSource              = 'Property', ...
    PRF                    = prf, ...
    RangeMethod            = 'FFT', ...
    RangeFFTLength         = nr, ...
    ReferenceRangeCentered = false);

fr = dca1000FileReader(recordLocation = recordLocation);

while fr.CurrentPosition <= fr.NumDataCubes
    iqData = read(fr, 1);
    iqData = iqData{1};

    % RX1 Range response
    iqDataRx1 = squeeze(iqData(:, 1, :));
    plotResponse(rangeresp, iqDataRx1);

    % RX1 TX1 Range-Doppler (TDM: 홀수 chirp = TX1)
    iqDataRx1Tx1 = squeeze(iqData(:, 1, 1:2:end));
    rdscope(iqDataRx1Tx1);
end
