function [controlPortNum, deviceType, configFile, adcDataFileName, captureFlag, recordingTime, numFrameDisplay] = configDialog(settingsFileName)      
if nargin<1, settingsFileName = ''; end
comPortsOptions = 1:100;
comPortChoice = arrayfun(@(c) sprintf('COM%d',c), comPortsOptions, 'UniformOutput', false);
comPortDefaults = comPortsOptions(1:2);

if exist(settingsFileName, 'file')
    [controlPortNum, deviceMode, configFileName, adcDataFileName] = readSettings(settingsFileName);
else   
    controlPortNum = comPortDefaults(1);
    deviceMode = 1;
    configFileName = '.\chirp_configs\xWRL6432_presenceDetection_3400.cfg';
    adcDataFileName = '.\data\test_6432.bin';
end

hDialog = dialog('Position',[300 370 500 300],'Name','Configuration');
uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[20 250 100 40],...
    'HorizontalAlignment','left',...
    'String','Select config port');

popup1 = uicontrol('Parent',hDialog,...
    'Style','popup',...
    'Position',[20 240 100 25],...
    'String',comPortChoice,...
    'Value', controlPortNum);

modeChoice = {'Raw Data Capture', '2D FFT output Playback'};         
uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[150 250 150 40],...
    'HorizontalAlignment','left',...
    'String','Mode Selection');

modePopup = uicontrol('Parent',hDialog,...
    'Style','popup',...
    'Position',[150 240 150 25],...
    'String',modeChoice,...
    'Value', 1);

deviceChoice = {'xWRL6432/xWRL1432', 'xWR6843/xWR1843/xWR1642', 'xWRL6844'};         
uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[320 250 150 40],...
    'HorizontalAlignment','left',...
    'String','Device Selection');

devicePopup = uicontrol('Parent',hDialog,...
    'Style','popup',...
    'Position',[320 240 150 25],...
    'String',deviceChoice,...
        'Value',deviceMode);
    %'Callback',@devicePickup_callback);

uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[20 180 200 40],...
    'HorizontalAlignment','left',...
    'String','Select chirp configuration file');

hFileName = uicontrol('Parent', hDialog,...
    'Style','text',...
    'Position',[20 160 360 40],...
    'HorizontalAlignment','left',...
    'String', configFileName);

hFileSelect = uicontrol('Parent',hDialog,...
    'Style', 'pushbutton',...
    'Position',[400 180 40 20],...
    'String','...',...
    'Callback',@configFileSelect_callback);

uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[20 120 200 40],...
    'HorizontalAlignment','left',...
    'String','Select raw data file');

hFileName2 = uicontrol('Parent', hDialog,...
    'Style','edit',...
    'Position',[20 100 260 40],...
    'HorizontalAlignment','left',...
    'String', adcDataFileName);

setappdata(hFileSelect,'configFileName', configFileName);

              
uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[20 60 150 20],...
    'HorizontalAlignment','left',...
    'String','Recording Time in second');

popup3 = uicontrol('Parent',hDialog,...
    'Style','edit',...
    'Position',[20 30 50 30],...
    'String','3',...
    'Value', 1);


uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[170 60 150 20],...
    'HorizontalAlignment','left',...
    'String','numFrame for display');

popup4 = uicontrol('Parent',hDialog,...
    'Style','edit',...
    'Position',[170 30 60 30],...
    'String','10',...
    'Value', 1);

uicontrol('Parent',hDialog,...
    'Position',[400 60 40 25],...
    'String','Go!',...
    'Callback',@go_callback);

% Wait for d to close before running to completion
uiwait(hDialog);
 
    function [pathname, filename] = configFileSelect_callback (source, ~)
        [filename, pathname] = uigetfile({'*.cfg'},...
            'Select Chirp configuration File', ...
            getappdata(source, 'configFileName'));
        hFileName.String = filename;
        setappdata(source, 'configFileName', [pathname, filename]);
    end

    function go_callback (~, ~)
        controlPortNum = popup1.Value; 
        controlPort = popup1.String{controlPortNum};     
        deviceMode = devicePopup.Value;
        deviceType = devicePopup.String{devicePopup.Value};
        configFile = getappdata(hFileSelect, 'configFileName');
        recordingTime = str2num(popup3.String);
        numFrameDisplay = str2num(popup4.String);
        adcDataFileName = hFileName2.String;
        if (modePopup.Value == 1)
            captureFlag = 1;
        else
            captureFlag = 0;
        end
        writeSettings(settingsFileName, controlPortNum, deviceMode, configFile, adcDataFileName);
        delete(gcf);
    end
end
